-- MySQL Script generated by MySQL Workbench
-- Tue 21 Jul 2020 01:31:57 PM
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema darq
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema darq
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `darq` ;
USE `darq` ;

-- -----------------------------------------------------
-- Table `darq`.`business_user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `darq`.`business_user` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `verified` TINYINT NOT NULL DEFAULT 0,
  `email` CHAR(128) NOT NULL,
  `password` CHAR(64) NOT NULL,
  `create_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `last_login` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE);


-- -----------------------------------------------------
-- Table `darq`.`business`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `darq`.`business` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `approved` TINYINT NOT NULL DEFAULT 0,
  `display_name` CHAR(64) NOT NULL,
  `display_picture` MEDIUMBLOB NOT NULL,
  `type` CHAR(32) NOT NULL,
  `sub_type` CHAR(64) NOT NULL,
  `calculated_rating` TINYINT NOT NULL DEFAULT 5,
  `props` JSON NULL,
  `owner` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_business_user1_idx` (`owner` ASC) VISIBLE,
  CONSTRAINT `fk_business_user1`
    FOREIGN KEY (`owner`)
    REFERENCES `darq`.`business_user` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `darq`.`personnel`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `darq`.`personnel` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `business_id` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `profession` VARCHAR(45) NOT NULL,
  `date_of_birth` DATE NOT NULL,
  `gender` ENUM('m', 'f') NOT NULL,
  `picture` CHAR(64) NOT NULL,
  `nationality` CHAR(32) NOT NULL,
  `marital_status` ENUM('single', 'married', 'divorced', 'widowed') NOT NULL,
  `religion` CHAR(16) NULL,
  `salary` FLOAT NULL,
  `education` ENUM('none', 'secondary', 'college', 'post-graduate') NULL,
  `languages` VARCHAR(128) NULL,
  `skills` VARCHAR(255) NULL,
  `experience` JSON NULL,
  PRIMARY KEY (`id`, `business_id`),
  INDEX `fk_personnel_business_idx` (`business_id` ASC) VISIBLE,
  CONSTRAINT `fk_personnel_business`
    FOREIGN KEY (`business_id`)
    REFERENCES `darq`.`business` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `darq`.`event`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `darq`.`event` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `owner` INT NOT NULL,
  `display_name` VARCHAR(255) NOT NULL,
  `display_picutre` MEDIUMBLOB NOT NULL,
  `type` CHAR(64) NOT NULL,
  `city` CHAR(64) NOT NULL,
  `start` TIMESTAMP NOT NULL,
  `end` TIMESTAMP NOT NULL,
  `props` JSON NULL,
  PRIMARY KEY (`id`, `owner`),
  INDEX `fk_event_user1_idx` (`owner` ASC) VISIBLE,
  CONSTRAINT `fk_event_user1`
    FOREIGN KEY (`owner`)
    REFERENCES `darq`.`business_user` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `darq`.`public_user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `darq`.`public_user` (
  `id` BIGINT NOT NULL,
  `create_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `last_login` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `first_name` VARCHAR(45) NULL,
  `last_name` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `darq`.`rating`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `darq`.`rating` (
  `business_id` INT NOT NULL,
  `public_user_id` BIGINT NOT NULL,
  `stars` TINYINT NOT NULL,
  PRIMARY KEY (`business_id`, `public_user_id`),
  INDEX `fk_rating_public_user1_idx` (`public_user_id` ASC) VISIBLE,
  CONSTRAINT `fk_rating_business1`
    FOREIGN KEY (`business_id`)
    REFERENCES `darq`.`business` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_rating_public_user1`
    FOREIGN KEY (`public_user_id`)
    REFERENCES `darq`.`public_user` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `darq`.`inquiry`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `darq`.`inquiry` (
  `business_id` INT NOT NULL,
  `public_user_id` BIGINT NOT NULL,
  `create_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `data` TEXT NOT NULL,
  `seen` TINYINT NOT NULL DEFAULT 0,
  INDEX `fk_inquiry_business1_idx` (`business_id` ASC) VISIBLE,
  INDEX `fk_inquiry_public_user1_idx` (`public_user_id` ASC) VISIBLE,
  PRIMARY KEY (`business_id`, `public_user_id`),
  CONSTRAINT `fk_inquiry_business1`
    FOREIGN KEY (`business_id`)
    REFERENCES `darq`.`business` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_inquiry_public_user1`
    FOREIGN KEY (`public_user_id`)
    REFERENCES `darq`.`public_user` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `darq`.`reply`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `darq`.`reply` (
  `create_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `inquiry_business_id` INT NOT NULL,
  `inquiry_public_user_id` BIGINT NOT NULL,
  `data` TEXT NOT NULL,
  `seen_by` TINYINT NOT NULL,
  PRIMARY KEY (`create_time`, `inquiry_business_id`, `inquiry_public_user_id`),
  INDEX `fk_reply_inquiry1_idx` (`inquiry_business_id` ASC, `inquiry_public_user_id` ASC) VISIBLE,
  CONSTRAINT `fk_reply_inquiry1`
    FOREIGN KEY (`inquiry_business_id` , `inquiry_public_user_id`)
    REFERENCES `darq`.`inquiry` (`business_id` , `public_user_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `darq`.`business_tentative_update`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `darq`.`business_tentative_update` (
  `business_id` INT NOT NULL,
  `updated_data` JSON NOT NULL,
  PRIMARY KEY (`business_id`),
  CONSTRAINT `fk_business_update_business1`
    FOREIGN KEY (`business_id`)
    REFERENCES `darq`.`business` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
